window.onload = function () {
  var table = new SortTable('scor-table',5,4);
  table.setUI();
  table.setData(0,0,"姓名");
  table.setData(1,0,"小明");
  table.setData(2,0,"小红");
  table.setData(3,0,"小Y");
  table.setData(4,0,"小Z");
  table.setData(0,1,"数学");
  table.setData(0,2,"物理");
  table.setData(0,3,"总分");
  table.setData(1,3,36);
  table.setData(2,3,1826);
  table.setData(3,3,25);
  table.setData(4,3,3);
  table.showSortButton(2);
  table.showSortButton(3);
  table.showSortButton(4);
  table.setData(1,1,33);
  table.setData(2,1,1820);
  table.setData(3,1,22);
  table.setData(4,1,-1);
  table.setData(1,2,3);
  table.setData(2,2,4);
  table.setData(3,2,3);
  table.setData(4,2,4);
};
